### ISSUE TITLE
support to 22.04 ?

### ISSUE THREAD

**Issue by changchichung** [tai271828/ubuntu-autoinstall-pxe-server#1]
any ideas how to support ubuntu 22.04 ?

**Comment by tai271828** [comment]
> any ideas how to support ubuntu 22.04 ?

If I remember correctly, this script do support 22.04. Is there anything wrong when you tried with 22.04?

**Comment by changchichung** [comment]
run this command
```
sudo ./setup-pxe-server.sh --url=https://releases.ubuntu.com/22.04/ubuntu-22.04-live-server-amd64.iso
====================================================================================
NOTE! You may want to clean the files previously downloaded.
sudo rm -rf /var/www/html/*.iso /var/lib/tftpboot/* ${HOME}/jammy-live-server-arm64
====================================================================================
```
then the script will cp "my rootfs" to /var/lib/tftpboot/

I think there might have some variables need to be fixed ??

**Comment by tai271828** [comment]
Hi, I tried the same command, and I could not reproduce the issue. Would you mind elaborating more details about your issue? 

For example,
1. the output of `ls /var/lib/tftpboot/`
2. invoke `set -x` before invoking `sudo ./setup-pxe-server.sh --url=https://releases.ubuntu.com/22.04/ubuntu-22.04-live-server-amd64.iso`

> run this command
> 
> ```
> sudo ./setup-pxe-server.sh --url=https://releases.ubuntu.com/22.04/ubuntu-22.04-live-server-amd64.iso
> ====================================================================================
> NOTE! You may want to clean the files previously downloaded.
> sudo rm -rf /var/www/html/*.iso /var/lib/tftpboot/* ${HOME}/jammy-live-server-arm64
> ====================================================================================
> ```
> 
> then the script will cp "my rootfs" to /var/lib/tftpboot/
> 
> I think there might have some variables need to be fixed ??

**Comment by changchichung** [comment]
I try to run the script in a new ubuntu 22.04 system and it works now.
